### ISSUE TITLE
Error when reading card

### ISSUE THREAD

**Issue by neilodiaz** [somq/nfccard-tool#1]
Hi,

Tried running `npm run read-nfcpcsc` but it returns me this error:

```

D:\Sort\project\node-nfc\nfccard-tool\examples\read-nfc-pcsc.js:12
  reader.on('card', async card => {
                    ^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

Any idea how can I fix this? Or maybe it's a bug? Thanks!

**Comment by neilodiaz** [comment]
Fixed it. This is due to outdated node version on my machine. Had to upgrade it to the latest. Everything's fine now. Thank you for this.
