### ISSUE TITLE
Failure TypeError: Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by rfedorczuk** [somq/nfccard-tool#5]
I got error like in title. 

I am simple using it like this:
```
reader
      .read(4, 16, 16)
      .then((cardHeader) => {
        return nfcCard.parseInfo(cardHeader);
      })
```

```
at Object.decimalToHexString (C:\Users\Radoslaw\Desktop\nfc-pcsc-master\nfc-pcsc-master\node_modules\nfccard-tool\lib\utils.js:56:21)
    at nfcCardTool.getHeaderRawValues (C:\Users\Radoslaw\Desktop\nfc-pcsc-master\nfc-pcsc-master\node_modules\nfccard-tool\lib\nfccard-tool.js:57:25)
    at nfcCardTool.parseInfo (C:\Users\Radoslaw\Desktop\nfc-pcsc-master\nfc-pcsc-master\node_modules\nfccard-tool\lib\nfccard-tool.js:274:32)
```

Card is Mifare classic.

**Comment by rfedorczuk** [comment]
fixed

**Comment by sikasep23** [comment]
> 4, 16, 16

how u fix this?
